/* 보안 */
DELETE FROM T_SECU_GROUP_AUTH;
DELETE FROM T_SECU_GROUP;
DELETE FROM T_SECU_USER;


/* 보안_사용자 */
DELETE FROM T_SECU_GROUP_USER;

INSERT INTO T_SECU_USER (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , EMAIL, PSWD, USE_FL
) VALUES (
    1, 0, 0, 1, 8, 0, 'Root Node', 'root'
  , 'NULL1', 'NULL', 0
);

INSERT INTO T_SECU_USER (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , EMAIL, PSWD, USE_FL
) VALUES (
    2, 1, 0, 2, 7, 1, '사용자', 'drive'
  , 'NULL2', 'NULL', 0
);

INSERT INTO T_SECU_USER (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , EMAIL, PSWD, USE_FL
) VALUES (
    3, 2, 0, 3, 4, 2, 'NULL', 'default'
  , 'guest', 'guest', 1
);

INSERT INTO T_SECU_USER (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , EMAIL, PSWD, USE_FL
) VALUES (
    4, 2, 1, 5, 6, 2, 'NULL', 'default'
  , 'admin', 'admin', 1
);

COMMIT;


/* 보안_그룹 */
INSERT INTO T_SECU_GROUP (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
) VALUES (
    1, 0, 0, 1, 8, 0, 'Root Node', 'root'
);

INSERT INTO T_SECU_GROUP (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
) VALUES (
    2, 1, 0, 2, 7, 1, '그룹', 'drive'
);

INSERT INTO T_SECU_GROUP (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
) VALUES (
    3, 2, 0, 3, 4, 2, '사용자', 'default'
);

INSERT INTO T_SECU_GROUP (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
) VALUES (
    4, 2, 1, 5, 6, 2, '관리자', 'default'
);

COMMIT;


/* 보안_그룹_권한 */
INSERT INTO T_SECU_GROUP_AUTH (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , GROUP_ID, AUTH
) VALUES (
    1, 0, 0, 1, 10, 0, 'Root Node', 'root'
  , 1, 'NULL'
);

INSERT INTO T_SECU_GROUP_AUTH (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , GROUP_ID, AUTH
) VALUES (
    2, 1, 0, 2, 9, 1, '그룹 권한', 'drive'
  , 2, 'NULL'
);

INSERT INTO T_SECU_GROUP_AUTH (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , GROUP_ID, AUTH
) 
SELECT 3, 2, 0, 3, 4, 2, 'NULL', 'default'
     , C_ID, 'ROLE_USER'
FROM T_SECU_GROUP
WHERE C_TITLE = '사용자';

INSERT INTO T_SECU_GROUP_AUTH (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , GROUP_ID, AUTH
) 
SELECT 4, 2, 1, 5, 6, 2, 'NULL', 'default'
     , C_ID, 'ROLE_USER'
FROM T_SECU_GROUP
WHERE C_TITLE = '관리자';

INSERT INTO T_SECU_GROUP_AUTH (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , GROUP_ID, AUTH
) 
SELECT 5, 2, 2, 7, 8, 2, 'NULL', 'default'
     , C_ID, 'ROLE_ADMIN'
FROM T_SECU_GROUP
WHERE C_TITLE = '관리자';

COMMIT;


/* 보안_그룹_사용자 */
INSERT INTO T_SECU_GROUP_USER (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , GROUP_ID, USER_ID
) VALUES (
    1, 0, 0, 1, 8, 0, 'Root Node', 'root'
  , 1, 1
);

INSERT INTO T_SECU_GROUP_USER (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , GROUP_ID, USER_ID
) VALUES (
    2, 1, 0, 2, 7, 1, '그룹', 'drive'
  , 2, 2
);

INSERT INTO T_SECU_GROUP_USER (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , GROUP_ID
  , USER_ID
)
SELECT 3, 2, 0, 3, 4, 2, 'NULL', 'default'
     , (SELECT C_ID FROM T_SECU_GROUP WHERE C_TITLE = '사용자')
     , (SELECT C_ID FROM T_SECU_USER WHERE EMAIL = 'guest')
FROM DUAL;

INSERT INTO T_SECU_GROUP_USER (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , GROUP_ID
  , USER_ID
)
SELECT 4, 2, 1, 5, 6, 2, 'NULL', 'default'
     , (SELECT C_ID FROM T_SECU_GROUP WHERE C_TITLE = '관리자')
     , (SELECT C_ID FROM T_SECU_USER WHERE EMAIL = 'admin')
FROM DUAL;

COMMIT;


/* 보안_로그인_리멤버미 */
DELETE FROM T_SECU_LOGIN_REMB_ME;

INSERT INTO T_SECU_LOGIN_REMB_ME (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , EMAIL, SERIES, TOKEN, LAST_USE_DT
) VALUES (
    1, 0, 0, 1, 4, 0, 'Root Node', 'root'
  , 'NULL', 'NULL1', 'NULL', SYSTIMESTAMP
);

INSERT INTO T_SECU_LOGIN_REMB_ME (
    C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE
  , EMAIL, SERIES, TOKEN, LAST_USE_DT
) VALUES (
    2, 1, 0, 2, 3, 1, '리멤버미', 'drive'
  , 'NULL', 'NULL2', 'NULL', SYSTIMESTAMP
);

COMMIT;