
DROP TABLE T_NEWSLETTER_COMPREHENSIVETREE;

CREATE TABLE T_NEWSLETTER_COMPREHENSIVETREE
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE),
  CONSTRAINT  T_NEWSLETTER_COMPREHENSIVETREE PRIMARY KEY (C_ID)
);

COMMENT ON TABLE T_NEWSLETTER_COMPREHENSIVETREE IS '뉴스레터';
COMMENT ON COLUMN T_NEWSLETTER_COMPREHENSIVETREE.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_NEWSLETTER_COMPREHENSIVETREE.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_NEWSLETTER_COMPREHENSIVETREE.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_NEWSLETTER_COMPREHENSIVETREE.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_NEWSLETTER_COMPREHENSIVETREE.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_NEWSLETTER_COMPREHENSIVETREE.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_NEWSLETTER_COMPREHENSIVETREE.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_NEWSLETTER_COMPREHENSIVETREE.C_TYPE IS '노드 타입';

DROP SEQUENCE S_NEWSLETTER_COMPREHENSIVETREE;

CREATE SEQUENCE S_NEWSLETTER_COMPREHENSIVETREE
  START WITH 7313
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;
