
DROP TABLE T_PRIMARY_COMPREHENSIVETREE;

CREATE TABLE T_PRIMARY_COMPREHENSIVETREE 
(
  C_ID NUMBER NOT NULL 
, C_PARENTID NUMBER NOT NULL 
, C_POSITION NUMBER NOT NULL 
, C_LEFT NUMBER NOT NULL 
, C_RIGHT NUMBER NOT NULL 
, C_LEVEL NUMBER NOT NULL 
, C_TITLE VARCHAR2(4000 BYTE) 
, C_TYPE VARCHAR2(4000 BYTE) 
, F_C_ID NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE STANDARD_DB_DAT 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

ALTER TABLE T_PRIMARY_COMPREHENSIVETREE
ADD CONSTRAINT T_PRIMARY_COMPREHENSIVETREE_FK FOREIGN KEY
(
  F_C_ID 
)
REFERENCES T_FOREIGN_COMPREHENSIVETREE
(
  C_ID 
)
ENABLE;

COMMENT ON TABLE T_PRIMARY_COMPREHENSIVETREE IS '주키 트리 스키마';

COMMENT ON COLUMN T_PRIMARY_COMPREHENSIVETREE.C_ID IS '노드 아이디';

COMMENT ON COLUMN T_PRIMARY_COMPREHENSIVETREE.C_PARENTID IS '부모 노드 아이디';

COMMENT ON COLUMN T_PRIMARY_COMPREHENSIVETREE.C_POSITION IS '노드 포지션';

COMMENT ON COLUMN T_PRIMARY_COMPREHENSIVETREE.C_LEFT IS '노드 좌측 끝 포인트';

COMMENT ON COLUMN T_PRIMARY_COMPREHENSIVETREE.C_RIGHT IS '노드 우측 끝 포인트';

COMMENT ON COLUMN T_PRIMARY_COMPREHENSIVETREE.C_LEVEL IS '노드 DEPTH ';

COMMENT ON COLUMN T_PRIMARY_COMPREHENSIVETREE.C_TITLE IS '노드 명';

COMMENT ON COLUMN T_PRIMARY_COMPREHENSIVETREE.C_TYPE IS '노드 타입';

COMMENT ON COLUMN T_PRIMARY_COMPREHENSIVETREE.F_C_ID IS '외래키 트리 스키마 노드 아이디';



DROP SEQUENCE S_PRIMARY_COMPREHENSIVETREE;

CREATE SEQUENCE S_PRIMARY_COMPREHENSIVETREE INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 0 CACHE 20;



DROP TABLE T_FOREIGN_COMPREHENSIVETREE;

CREATE TABLE T_FOREIGN_COMPREHENSIVETREE 
(
  C_ID NUMBER NOT NULL 
, C_PARENTID NUMBER NOT NULL 
, C_POSITION NUMBER NOT NULL 
, C_LEFT NUMBER NOT NULL 
, C_RIGHT NUMBER NOT NULL 
, C_LEVEL NUMBER NOT NULL 
, C_TITLE VARCHAR2(4000 BYTE) 
, C_TYPE VARCHAR2(4000 BYTE) 
, CONSTRAINT T_FOREIGN_COMPREHENSIVETREE_PK PRIMARY KEY 
  (
    C_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX T_FOREIGN_COMPREHENSIVETREE_PK ON T_FOREIGN_COMPREHENSIVETREE (C_ID ASC) 
      LOGGING 
      TABLESPACE STANDARD_DB_DAT 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE STANDARD_DB_DAT 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

COMMENT ON TABLE T_FOREIGN_COMPREHENSIVETREE IS '외래키 트리 스키마';

COMMENT ON COLUMN T_FOREIGN_COMPREHENSIVETREE.C_ID IS '노드 아이디';

COMMENT ON COLUMN T_FOREIGN_COMPREHENSIVETREE.C_PARENTID IS '부모 노드 아이디';

COMMENT ON COLUMN T_FOREIGN_COMPREHENSIVETREE.C_POSITION IS '노드 포지션';

COMMENT ON COLUMN T_FOREIGN_COMPREHENSIVETREE.C_LEFT IS '노드 좌측 끝 포인트';

COMMENT ON COLUMN T_FOREIGN_COMPREHENSIVETREE.C_RIGHT IS '노드 우측 끝 포인트';

COMMENT ON COLUMN T_FOREIGN_COMPREHENSIVETREE.C_LEVEL IS '노드 DEPTH ';

COMMENT ON COLUMN T_FOREIGN_COMPREHENSIVETREE.C_TITLE IS '노드 명';

COMMENT ON COLUMN T_FOREIGN_COMPREHENSIVETREE.C_TYPE IS '노드 타입';



DROP SEQUENCE S_FOREIGN_COMPREHENSIVETREE;

CREATE SEQUENCE S_FOREIGN_COMPREHENSIVETREE INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 0 CACHE 20;
