/* 고급설정_서버 */
CREATE TABLE T_CORE_SETTING_SERVER (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_URL VARCHAR2(255), /* 기본URL */
	C_SSL_FL CHAR(1) DEFAULT 0, /* SSL사용여부 */
	C_HTTP_PORT VARCHAR2(255), /* HTTP포트 */
	C_HTTPS_PORT VARCHAR2(255), /* HTTPS포트 */
	C_SHORT_URL_FL CHAR(1) DEFAULT 0, /* 짧은주소사용여부 */
	C_SSO_FL CHAR(1) DEFAULT 0 /* SSO사용여부 */
);

COMMENT ON TABLE T_CORE_SETTING_SERVER IS '고급설정_서버';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_URL IS '기본URL';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_SSL_FL IS 'SSL사용여부';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_HTTP_PORT IS 'HTTP포트';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_HTTPS_PORT IS 'HTTPS포트';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_SHORT_URL_FL IS '짧은주소사용여부';

COMMENT ON COLUMN T_CORE_SETTING_SERVER.C_SSO_FL IS 'SSO사용여부';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_SERVER
	ON T_CORE_SETTING_SERVER (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_SERVER
	ADD
		CONSTRAINT PK_T_CORE_SETTING_SERVER
		PRIMARY KEY (
			C_ID
		);

/* 트리거 고급설정_서버 */
/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
DROP TABLE T_CORE_SETTING_SERVER_LOG;

CREATE TABLE T_CORE_SETTING_SERVER_LOG
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE),
  C_METHOD    VARCHAR2(4000 BYTE),
  C_STATE     VARCHAR2(4000 BYTE),
  C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_CORE_SETTING_SERVER_LOG IS '고급설정_서버 스키마 트리거 로그';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_CORE_SETTING_SERVER_LOG.C_DATE IS '노드 변경 시'; 

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER TRIGGER_CORE_SETTING_SERVER
BEFORE DELETE OR INSERT OR UPDATE
ON T_CORE_SETTING_SERVER
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;
    IF UPDATING  THEN    
        insert into T_CORE_SETTING_SERVER_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);        
        insert into T_CORE_SETTING_SERVER_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);   
     END IF;
    IF DELETING THEN
        insert into T_CORE_SETTING_SERVER_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
    END IF;   
    IF INSERTING  THEN
        insert into T_CORE_SETTING_SERVER_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
    END IF;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END TRIGGER_CORE_SETTING_SERVER;

/* 고급설정_FTP */
CREATE TABLE T_CORE_SETTING_FTP (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_FTP_ID VARCHAR2(4000), /* FTP아이디 */
	C_FTP_PASSWORD VARCHAR2(4000), /* FTP비밀번호 */
	C_FTP_URL VARCHAR2(255), /* FTP주소 */
	C_FTP_PORT VARCHAR2(255), /* FTP포트 */
	C_PASSIVE_FL CHAR(1) DEFAULT 0, /* PASSIVE사용여부 */
	C_SFTP_FL CHAR(1) DEFAULT 0 /* SFTP사용여부 */
);

COMMENT ON TABLE T_CORE_SETTING_FTP IS '고급설정_FTP';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_FTP_ID IS 'FTP아이디';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_FTP_PASSWORD IS 'FTP비밀번호';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_FTP_URL IS 'FTP주소';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_FTP_PORT IS 'FTP포트';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_PASSIVE_FL IS 'PASSIVE사용여부';

COMMENT ON COLUMN T_CORE_SETTING_FTP.C_SFTP_FL IS 'SFTP사용여부';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_FTP
	ON T_CORE_SETTING_FTP (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_FTP
	ADD
		CONSTRAINT PK_T_CORE_SETTING_FTP
		PRIMARY KEY (
			C_ID
		);

/* 트리거 고급설정_FTP */
/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
CREATE TABLE T_CORE_SETTING_FTP_LOG
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE),
  C_METHOD    VARCHAR2(4000 BYTE),
  C_STATE     VARCHAR2(4000 BYTE),
  C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_CORE_SETTING_FTP_LOG IS '고급설정_FTP 스키마 트리거 로그';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_CORE_SETTING_FTP_LOG.C_DATE IS '노드 변경 시'; 

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER TRIGGER_CORE_SETTING_FTP
BEFORE DELETE OR INSERT OR UPDATE
ON T_CORE_SETTING_FTP
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;
    IF UPDATING  THEN    
        insert into T_CORE_SETTING_FTP_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);        
        insert into T_CORE_SETTING_FTP_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);   
     END IF;
    IF DELETING THEN
        insert into T_CORE_SETTING_FTP_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
    END IF;   
    IF INSERTING  THEN
        insert into T_CORE_SETTING_FTP_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
    END IF;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END TRIGGER_CORE_SETTING_FTP;

/* 고급설정_파일업로드 */
CREATE TABLE T_CORE_SETTING_UPLOAD (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_FILE_SIZE_LIMIT VARCHAR2(255), /* 파일크기제한 */
	C_DOCUMENT_SIZE_LIMIT VARCHAR2(255), /* 문서파일크기제한 */
	C_FILE_EXT_LIMIT VARCHAR2(255), /* 파일확장자제한 */
	C_EXTERNAL_LINK_FL CHAR(1) DEFAULT 0, /* 외부링크사용여부 */
	C_EXTERNAL_LINK_ALLOWED_EXT VARCHAR2(255), /* 외부링크허용확장자 */
	C_EXTERNAL_LINK_ALLOWED_SITE VARCHAR2(255) /* 외부링크허용사이트 */
);

COMMENT ON TABLE T_CORE_SETTING_UPLOAD IS '고급설정_파일업로드';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_FILE_SIZE_LIMIT IS '파일크기제한';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_DOCUMENT_SIZE_LIMIT IS '문서파일크기제한';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_FILE_EXT_LIMIT IS '파일확장자제한';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_EXTERNAL_LINK_FL IS '외부링크사용여부';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_EXTERNAL_LINK_ALLOWED_EXT IS '외부링크허용확장자';

COMMENT ON COLUMN T_CORE_SETTING_UPLOAD.C_EXTERNAL_LINK_ALLOWED_SITE IS '외부링크허용사이트';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_UPLOAD
	ON T_CORE_SETTING_UPLOAD (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_UPLOAD
	ADD
		CONSTRAINT PK_T_CORE_SETTING_UPLOAD
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_컴포넌트 */
CREATE TABLE T_CORE_SETTING_ADDON_COMPN (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_COMPN_TITLE VARCHAR2(255), /* 컴포넌트명 */
	C_COMPN_VERSION VARCHAR2(255), /* 컴포넌트버전 */
	C_COMPN_AUTHOR VARCHAR2(255), /* 컴포넌트작성자 */
	C_COMPN_PATH VARCHAR2(255) /* 컴포넌트설치경로 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_COMPN IS '고급설정_설치프로그램_컴포넌트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_COMPN_TITLE IS '컴포넌트명';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_COMPN_VERSION IS '컴포넌트버전';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_COMPN_AUTHOR IS '컴포넌트작성자';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_COMPN.C_COMPN_PATH IS '컴포넌트설치경로';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_ADDON_COMPN
	ON T_CORE_SETTING_ADDON_COMPN (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_COMPN
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_COMPN
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_레이아웃 */
CREATE TABLE T_CORE_SETTING_ADDON_LAYOUT (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_LAYOUT_TITLE VARCHAR2(255), /* 레이아웃명 */
	C_LAYOUT_VERSION VARCHAR2(255), /* 레이아웃버전 */
	C_LAYOUT_AUTHOR VARCHAR2(255), /* 레이아웃작성자 */
	C_LAYOUT_PATH VARCHAR2(255), /* 레이아웃설치경로 */
	C_HTML VARCHAR2(4000), /* 레이아웃HTML */
	C_CSS VARCHAR2(4000) /* 레이아웃CSS */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_LAYOUT IS '고급설정_설치프로그램_레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_LAYOUT_TITLE IS '레이아웃명';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_LAYOUT_VERSION IS '레이아웃버전';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_LAYOUT_AUTHOR IS '레이아웃작성자';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_LAYOUT_PATH IS '레이아웃설치경로';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_HTML IS '레이아웃HTML';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_LAYOUT.C_CSS IS '레이아웃CSS';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_ADDON_LAYOUT
	ON T_CORE_SETTING_ADDON_LAYOUT (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_LAYOUT
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_LAYOUT
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_레이아웃_파일 */
CREATE TABLE T_CORE_SETTING_LAYOUT_FILE (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_FILE_TYPE VARCHAR2(100), /* 파일타입 */
	C_PATH VARCHAR2(255), /* 파일경로 */
	C_LAYOUT_ID NUMBER /* 레이아웃매핑아이디 */
);

COMMENT ON TABLE T_CORE_SETTING_LAYOUT_FILE IS '고급설정_설치프로그램_레이아웃_파일';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_FILE_TYPE IS '파일타입';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_PATH IS '파일경로';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_FILE.C_LAYOUT_ID IS '레이아웃매핑아이디';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_LAYOUT_FILE
	ON T_CORE_SETTING_LAYOUT_FILE (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_LAYOUT_FILE
	ADD
		CONSTRAINT PK_T_CORE_SETTING_LAYOUT_FILE
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_위젯 */
CREATE TABLE T_CORE_SETTING_ADDON_WIDGET (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_WIDGET_TITLE VARCHAR2(255), /* 위젯명 */
	C_WIDGET_VERSION VARCHAR2(255), /* 위젯버전 */
	C_WIDGET_AUTHOR VARCHAR2(255), /* 위젯작성자 */
	C_WIDGET_PATH VARCHAR2(255), /* 위젯설치경로 */
	C_WIDGET_SKIN_ID NUMBER, /* 위젯스킨아이디 */
	C_WIDGET_CONTENTS_ID NUMBER, /* 위젯컨텐츠 */
	C_WIDGET_CONTENTS_TYPE_ID NUMBER, /* 위젯컨텐츠타입아이디 */
	C_WIDGET_HTML_TYPE NUMBER, /* 위젯HTML출력방식아이디 */
	C_WIDGET_LIST_COUNT INTEGER, /* 위젯목록수 */
	C_WIDGET_PAGE_COUNT INTEGER, /* 위젯페이지수 */
	C_WIDGET_TITLE_LENGTH INTEGER, /* 위젯제목글자수 */
	C_WIDGET_AUTHER_LENGTH INTEGER, /* 위젯작성자글자수 */
	C_WIDGET_CONTENTS_LENGTH INTEGER, /* 위젯내용글자수 */
	C_WIDGET_LINK_TYPE_ID NUMBER, /* 위젯링크타입아이디 */
	C_WIDGET_SORT_ID NUMBER, /* 위젯정렬대상아이디 */
	C_WIDGET_SORT_METHOD_ID NUMBER, /* 위젯정렬방법아이디 */
	C_WIDGET_THUM_ID NUMBER, /* 위젯썸네일아이디 */
	C_WIDGET_IMAGE_WIDTH INTEGER, /* 위젯이미지가로크기 */
	C_WIDGET_IMAGE_HEIGHT INTEGER, /* 위젯이미지세로크기 */
	C_MENU_ID NUMBER /* 메뉴매핑아이디 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_WIDGET IS '고급설정_설치프로그램_위젯';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_TITLE IS '위젯명';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_VERSION IS '위젯버전';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_AUTHOR IS '위젯작성자';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_PATH IS '위젯설치경로';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_SKIN_ID IS '위젯스킨아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_CONTENTS_ID IS '위젯컨텐츠';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_CONTENTS_TYPE_ID IS '위젯컨텐츠타입아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_HTML_TYPE IS '위젯HTML출력방식아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_LIST_COUNT IS '위젯목록수';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_PAGE_COUNT IS '위젯페이지수';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_TITLE_LENGTH IS '위젯제목글자수';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_AUTHER_LENGTH IS '위젯작성자글자수';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_CONTENTS_LENGTH IS '위젯내용글자수';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_LINK_TYPE_ID IS '위젯링크타입아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_SORT_ID IS '위젯정렬대상아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_SORT_METHOD_ID IS '위젯정렬방법아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_THUM_ID IS '위젯썸네일아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_IMAGE_WIDTH IS '위젯이미지가로크기';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_WIDGET_IMAGE_HEIGHT IS '위젯이미지세로크기';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET.C_MENU_ID IS '메뉴매핑아이디';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_ADDON_WIDGET
	ON T_CORE_SETTING_ADDON_WIDGET (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_WIDGET
		PRIMARY KEY (
			C_ID
		);

/* 메뉴 */
CREATE TABLE T_CORE_MENU (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_MENU_ID NUMBER, /* 메뉴아이디 */
	C_PAGE_MAPPING_ID NUMBER, /* 메뉴페이지매핑아이디 */
	C_AUTH_ID NUMBER, /* 접근권한매핑아이디 */
	C_IMAGE_DEAULT NUMBER, /* 메뉴링크이미지기본 */
	C_IMAGE_HOVER NUMBER, /* 메뉴링크이미지마우스오버 */
	C_IMAGE_SELECTED NUMBER, /* 메뉴링크이미지선택시 */
	C_HOME_FL CHAR(1) DEFAULT 0 /* 홈화면설정 */
);

COMMENT ON TABLE T_CORE_MENU IS '메뉴';

COMMENT ON COLUMN T_CORE_MENU.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_MENU.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_MENU.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_MENU.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_MENU.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_MENU.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_MENU.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_MENU.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_MENU.C_MENU_ID IS '메뉴아이디';

COMMENT ON COLUMN T_CORE_MENU.C_PAGE_MAPPING_ID IS '메뉴페이지매핑아이디';

COMMENT ON COLUMN T_CORE_MENU.C_AUTH_ID IS '접근권한매핑아이디';

COMMENT ON COLUMN T_CORE_MENU.C_IMAGE_DEAULT IS '메뉴링크이미지기본';

COMMENT ON COLUMN T_CORE_MENU.C_IMAGE_HOVER IS '메뉴링크이미지마우스오버';

COMMENT ON COLUMN T_CORE_MENU.C_IMAGE_SELECTED IS '메뉴링크이미지선택시';

COMMENT ON COLUMN T_CORE_MENU.C_HOME_FL IS '홈화면설정';

CREATE UNIQUE INDEX PK_T_CORE_MENU
	ON T_CORE_MENU (
		C_ID ASC
	);

ALTER TABLE T_CORE_MENU
	ADD
		CONSTRAINT PK_T_CORE_MENU
		PRIMARY KEY (
			C_ID
		);

/* 페이지 */
CREATE TABLE T_CORE_PAGE (
	C_ID NUMBER NOT NULL, /* 메뉴페이지매핑아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_PAGE_ID VARCHAR2(255), /* 페이지아이디 */
	C_REG_NM VARCHAR2(255), /* 생성자 */
	C_REG_DT CHAR(14), /* 생성일자 */
	C_EXPIRY_DT CHAR(14), /* 유효기간 */
	C_APPLY_FL CHAR(1) DEFAULT 0, /* 적용여부 */
	C_PAGE_CONTENTS VARCHAR2(4000), /* 페이지내용 */
	C_WIDGET_ID NUMBER /* 위젯매핑아이디 */
);

COMMENT ON TABLE T_CORE_PAGE IS '페이지';

COMMENT ON COLUMN T_CORE_PAGE.C_ID IS '메뉴페이지매핑아이디';

COMMENT ON COLUMN T_CORE_PAGE.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_PAGE.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_PAGE.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_PAGE.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_PAGE.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_PAGE.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_PAGE.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_PAGE.C_PAGE_ID IS '페이지아이디';

COMMENT ON COLUMN T_CORE_PAGE.C_REG_NM IS '생성자';

COMMENT ON COLUMN T_CORE_PAGE.C_REG_DT IS '생성일자';

COMMENT ON COLUMN T_CORE_PAGE.C_EXPIRY_DT IS '유효기간';

COMMENT ON COLUMN T_CORE_PAGE.C_APPLY_FL IS '적용여부';

COMMENT ON COLUMN T_CORE_PAGE.C_PAGE_CONTENTS IS '페이지내용';

COMMENT ON COLUMN T_CORE_PAGE.C_WIDGET_ID IS '위젯매핑아이디';

CREATE UNIQUE INDEX PK_T_CORE_PAGE
	ON T_CORE_PAGE (
		C_ID ASC
	);

ALTER TABLE T_CORE_PAGE
	ADD
		CONSTRAINT PK_T_CORE_PAGE
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_후보군 */
CREATE TABLE T_CORE_SETTING_ADDON_RESERVE (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_RESERVE_TITLE VARCHAR2(255), /* 후보군명 */
	C_RESERVE_VERSION VARCHAR2(255), /* 후보군버전 */
	C_RESERVE_AUTHOR VARCHAR2(255), /* 후보군작성자 */
	C_RESERVE_TYPE_ID NUMBER, /* 후보군타입아이디 */
	C_RESERVE_USE_FL VARCHAR2(255) /* 후보군설치여부 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_RESERVE IS '고급설정_설치프로그램_후보군';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_RESERVE_TITLE IS '후보군명';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_RESERVE_VERSION IS '후보군버전';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_RESERVE_AUTHOR IS '후보군작성자';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_RESERVE_TYPE_ID IS '후보군타입아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE.C_RESERVE_USE_FL IS '후보군설치여부';

CREATE UNIQUE INDEX PK_T_CORE_STNG_ADN_RESERVE
	ON T_CORE_SETTING_ADDON_RESERVE (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_RESERVE
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_RESERVE
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_후보군_타입 */
CREATE TABLE T_CORE_SETTING_ADDON_RESERVE_TYPE (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_RESERVE_TYPE IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE_TYPE.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE_TYPE.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE_TYPE.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE_TYPE.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE_TYPE.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE_TYPE.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE_TYPE.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_RESERVE_TYPE.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CR_STNG_ADN_RSRV_TYPE
	ON T_CORE_SETTING_ADDON_RESERVE_TYPE (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_RESERVE_TYPE
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_RESERVE_TYPE
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_위젯_스킨 */
CREATE TABLE T_CORE_SETTING_ADDON_WIDGET_SKIN (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_WIDGET_SKIN IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SKIN.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SKIN.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SKIN.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SKIN.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SKIN.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SKIN.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SKIN.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SKIN.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CR_STNG_ADN_WDGT_SKIN
	ON T_CORE_SETTING_ADDON_WIDGET_SKIN (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET_SKIN
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_WIDGET_SKIN
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_위젯_컨텐츠 */
CREATE TABLE T_CORE_SETTING_ADDON_WIDGET_CONTENTS (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_WIDGET_CONTENTS IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CR_ADN_WDGT_CNTNTS
	ON T_CORE_SETTING_ADDON_WIDGET_CONTENTS (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET_CONTENTS
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_WIDGET_CONTENTS
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_위젯_컨텐츠_타입 */
CREATE TABLE T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CR_STNG_CNTNTS_TP
	ON T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_위젯_HTML */
CREATE TABLE T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CR_STNG_WDGT_HTML_TP
	ON T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_위젯_링크 */
CREATE TABLE T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CR_STNG_WDGT_LNK_TP
	ON T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_위젯_정렬대상 */
CREATE TABLE T_CORE_SETTING_ADDON_WIDGET_SORT (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_WIDGET_SORT IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CR_STNG_ADN_WDGT_SORT
	ON T_CORE_SETTING_ADDON_WIDGET_SORT (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET_SORT
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_WIDGET_SORT
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_위젯_정렬방법 */
CREATE TABLE T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CR_STNG_WDGT_SRT_MTHD
	ON T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD
		PRIMARY KEY (
			C_ID
		);

/* 고급설정_설치프로그램_위젯_썸네일 */
CREATE TABLE T_CORE_SETTING_ADDON_WIDGET_THUM (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_WIDGET_THUM IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_THUM.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_THUM.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_THUM.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_THUM.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_THUM.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_THUM.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_THUM.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_THUM.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CR_STNG_ADN_WDGT_THUMB
	ON T_CORE_SETTING_ADDON_WIDGET_THUM (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET_THUM
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_WIDGET_THUMB
		PRIMARY KEY (
			C_ID
		);

/* 메뉴_접근권한 */
CREATE TABLE T_MENU_AUTH (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_AUTH VARCHAR2(100) /* 접근권한 */
);

COMMENT ON TABLE T_MENU_AUTH IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_MENU_AUTH.C_ID IS '노드아이디';

COMMENT ON COLUMN T_MENU_AUTH.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_MENU_AUTH.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_MENU_AUTH.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_MENU_AUTH.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_MENU_AUTH.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_MENU_AUTH.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_MENU_AUTH.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_MENU_AUTH.C_AUTH IS '접근권한';

CREATE UNIQUE INDEX PK_T_MENU_AUTH
	ON T_MENU_AUTH (
		C_ID ASC
	);

ALTER TABLE T_MENU_AUTH
	ADD
		CONSTRAINT PK_T_MENU_AUTH
		PRIMARY KEY (
			C_ID
		);

/* 일반설정_썸네일_방법 */
CREATE TABLE T_CORE_SETTING_THUM_METHOD (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_THUM_METHOD IS '일반설정_썸네일_방법';

COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_THUM_METHOD
	ON T_CORE_SETTING_THUM_METHOD (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_THUM_METHOD
	ADD
		CONSTRAINT PK_T_CORE_SETTING_THUM_METHOD
		PRIMARY KEY (
			C_ID
		);

/* 트리거_일반설정_섬네일_형식 */
/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
CREATE TABLE T_CORE_SETTING_THUM_METHOD_LOG
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE)                            NOT NULL,
  C_METHOD    VARCHAR2(4000 BYTE),
  C_STATE     VARCHAR2(4000 BYTE),
  C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_CORE_SETTING_THUM_METHOD_LOG IS '기본 트리 스키마 트리거 로그';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_CORE_SETTING_THUM_METHOD_LOG.C_DATE IS '노드 변경 시'; 

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER TRIGGER_CORE_SETTING_THUM_METHOD
BEFORE DELETE OR INSERT OR UPDATE
ON T_CORE_SETTING_THUM_METHOD
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;
    IF UPDATING  THEN    
        insert into T_CORE_SETTING_THUM_METHOD_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);        
        insert into T_CORE_SETTING_THUM_METHOD_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);   
     END IF;
    IF DELETING THEN
        insert into T_CORE_SETTING_THUM_METHOD_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
    END IF;   
    IF INSERTING  THEN
        insert into T_CORE_SETTING_THUM_METHOD_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
    END IF;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END TRIGGER_CORE_SETTING_THUM_METHOD;

/* 코어_설정_팝업 */
CREATE TABLE T_CORE_SETTING_POPUP (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_POPUP_CONTENT VARCHAR2(4000), /* 팝업내용 */
	C_WRITNG_DE CHAR(8), /* 작성일자 */
	C_EXPIRY_DE CHAR(8), /* 유효기일 */
	C_APPLY_FL CHAR(1) DEFAULT 0, /* 적용여부 */
	C_RE_POPUP_TERM INTEGER, /* 재팝업기간 */
	C_LAYER_LEFT INTEGER, /* 레이어좌측 */
	C_LAYER_TOP INTEGER, /* 레이어상단 */
	C_LAYER_WIDTH INTEGER, /* 레이어가로 */
	C_LAYER_HEIGHT INTEGER /* 레이어세로 */
);

COMMENT ON TABLE T_CORE_SETTING_POPUP IS '코어_설정_팝업';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_POPUP_CONTENT IS '팝업내용';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_WRITNG_DE IS '작성일자';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_EXPIRY_DE IS '유효기일';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_APPLY_FL IS '적용여부';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_RE_POPUP_TERM IS '재팝업기간';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_LAYER_LEFT IS '레이어좌측';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_LAYER_TOP IS '레이어상단';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_LAYER_WIDTH IS '레이어가로';

COMMENT ON COLUMN T_CORE_SETTING_POPUP.C_LAYER_HEIGHT IS '레이어세로';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_POPUP
	ON T_CORE_SETTING_POPUP (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_POPUP
	ADD
		CONSTRAINT PK_T_CORE_SETTING_POPUP
		PRIMARY KEY (
			C_ID
		);

/* 일반설정_시간_포맷 */
CREATE TABLE T_CORE_SETTING_TIME_FORMAT (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_TIME_FORMAT IS '일반설정_시간_포맷';

COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_TIME_FORMAT
	ON T_CORE_SETTING_TIME_FORMAT (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_TIME_FORMAT
	ADD
		CONSTRAINT PK_T_CORE_SETTING_TIME_FORMAT
		PRIMARY KEY (
			C_ID
		);

/* 트리거 일반설정_시간_포맷 */
/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
CREATE TABLE T_CORE_SETTING_TIME_FORMAT_LOG
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE)                            NOT NULL,
  C_METHOD    VARCHAR2(4000 BYTE),
  C_STATE     VARCHAR2(4000 BYTE),
  C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_CORE_SETTING_TIME_FORMAT_LOG IS '기본 트리 스키마 트리거 로그';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_CORE_SETTING_TIME_FORMAT_LOG.C_DATE IS '노드 변경 시'; 

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER TRIGGER_CORE_SETTING_TIME_FORMAT
BEFORE DELETE OR INSERT OR UPDATE
ON T_CORE_SETTING_TIME_FORMAT
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;
    IF UPDATING  THEN    
        insert into T_CORE_SETTING_TIME_FORMAT_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);        
        insert into T_CORE_SETTING_TIME_FORMAT_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);   
     END IF;
    IF DELETING THEN
        insert into T_CORE_SETTING_TIME_FORMAT_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
    END IF;   
    IF INSERTING  THEN
        insert into T_CORE_SETTING_TIME_FORMAT_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
    END IF;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END TRIGGER_CORE_SETTING_TIME_FORMAT;

/* 일반설정_현지_시간 */
CREATE TABLE T_CORE_SETTING_LOCAL_TIME (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_LOCAL_TIME IS '일반설정_현지_시간';

COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_LOCAL_TIME
	ON T_CORE_SETTING_LOCAL_TIME (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_LOCAL_TIME
	ADD
		CONSTRAINT PK_T_CORE_SETTING_LOCAL_TIME
		PRIMARY KEY (
			C_ID
		);

/* 트리거 일반설정_현지_시간 */
/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
CREATE TABLE T_CORE_SETTING_LOCAL_TIME_LOG
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE)                            NOT NULL,
  C_METHOD    VARCHAR2(4000 BYTE),
  C_STATE     VARCHAR2(4000 BYTE),
  C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_CORE_SETTING_LOCAL_TIME_LOG IS '일반설정_현지시간 스키마 트리거 로그';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_CORE_SETTING_LOCAL_TIME_LOG.C_DATE IS '노드 변경 시'; 

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER TRIGGER_CORE_SETTING_LOCAL_TIME
BEFORE DELETE OR INSERT OR UPDATE
ON T_CORE_SETTING_LOCAL_TIME
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;
    IF UPDATING  THEN    
        insert into T_CORE_SETTING_LOCAL_TIME_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);        
        insert into T_CORE_SETTING_LOCAL_TIME_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);   
     END IF;
    IF DELETING THEN
        insert into T_CORE_SETTING_LOCAL_TIME_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
    END IF;   
    IF INSERTING  THEN
        insert into T_CORE_SETTING_LOCAL_TIME_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
    END IF;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END TRIGGER_CORE_SETTING_LOCAL_TIME;

/* 코어_설정_SNS */
CREATE TABLE T_CORE_SETTING_SNS (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_API_KEY VARCHAR2(4000), /* API키 */
	C_API_PASSWORD VARCHAR2(4000) /* API패스워드 */
);

COMMENT ON TABLE T_CORE_SETTING_SNS IS '코어_설정_SNS';

COMMENT ON COLUMN T_CORE_SETTING_SNS.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_SNS.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_SNS.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_SNS.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_SNS.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_SNS.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_SNS.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_SNS.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_SNS.C_API_KEY IS 'API키';

COMMENT ON COLUMN T_CORE_SETTING_SNS.C_API_PASSWORD IS 'API패스워드';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_SNS
	ON T_CORE_SETTING_SNS (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_SNS
	ADD
		CONSTRAINT PK_T_CORE_SETTING_SNS
		PRIMARY KEY (
			C_ID
		);

/* 일반설정_레이아웃 */
CREATE TABLE T_CORE_SETTING_LAYOUT (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_LAYOUT IS '일반설정_레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_LAYOUT.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_LAYOUT
	ON T_CORE_SETTING_LAYOUT (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_LAYOUT
	ADD
		CONSTRAINT PK_T_CORE_SETTING_LAYOUT
		PRIMARY KEY (
			C_ID
		);

/* 트리거_일반설정_레이아웃 */
/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
CREATE TABLE T_CORE_SETTING_LAYOUT_LOG
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE)                            NOT NULL,
  C_METHOD    VARCHAR2(4000 BYTE),
  C_STATE     VARCHAR2(4000 BYTE),
  C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_CORE_SETTING_LAYOUT_LOG IS '기본 트리 스키마 트리거 로그';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_CORE_SETTING_LAYOUT_LOG.C_DATE IS '노드 변경 시'; 

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER TRIGGER_CORE_SETTING_LAYOUT
BEFORE DELETE OR INSERT OR UPDATE
ON T_CORE_SETTING_LAYOUT
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;
    IF UPDATING  THEN    
        insert into T_CORE_SETTING_LAYOUT_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);        
        insert into T_CORE_SETTING_LAYOUT_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);   
     END IF;
    IF DELETING THEN
        insert into T_CORE_SETTING_LAYOUT_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
    END IF;   
    IF INSERTING  THEN
        insert into T_CORE_SETTING_LAYOUT_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
    END IF;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END TRIGGER_CORE_SETTING_LAYOUT;

/* 일반설정_기본 */
CREATE TABLE T_CORE_SETTING_BASIC (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_SITE_TITLE VARCHAR2(200), /* 사이트제목 */
	C_BASIC_LANGUAGE_ID NUMBER, /* 기본언어아이디 */
	C_LOCAL_TIME_ID NUMBER, /* 현지시간아이디 */
	C_TIME_FORMAT_ID NUMBER, /* 시간포맷아이디 */
	C_THUM_CREAT_METHOD_ID NUMBER, /* 썸네일생성방법아이디 */
	C_FAVICON_USE_FL CHAR(1) DEFAULT 0, /* 파비콘적용여부 */
	C_FAVICON_FILE_ID NUMBER, /* 파비콘파일아이디 */
	C_MOBILE_ICON_APPLY_FL CHAR(1) DEFAULT 0, /* 모바일아이콘적용여부 */
	C_MOBILE_ICON_FILE_ID NUMBER, /* 모바일아이콘파일아이디 */
	C_LAYOUT_ID NUMBER, /* 레이아웃설정아이디 */
	C_ALLOW_URL_ID NUMBER, /* 허용URL아이디 */
	C_ALLOW_IP_ID NUMBER, /* 허용IP아이디 */
	C_ACCES_PROH_WORDS VARCHAR2(4000), /* 접근금지문구 */
	C_USER_JOIN_USE_FL CHAR(1) DEFAULT 0, /* 회원가입사용여부 */
	C_FOOTER_SCRIPT VARCHAR2(4000) /* 하단스크립트 */
);

COMMENT ON TABLE T_CORE_SETTING_BASIC IS '일반설정_기본';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_SITE_TITLE IS '사이트제목';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_BASIC_LANGUAGE_ID IS '기본언어아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_LOCAL_TIME_ID IS '현지시간아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_TIME_FORMAT_ID IS '시간포맷아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_THUM_CREAT_METHOD_ID IS '썸네일생성방법아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_FAVICON_USE_FL IS '파비콘적용여부';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_FAVICON_FILE_ID IS '파비콘파일아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_MOBILE_ICON_APPLY_FL IS '모바일아이콘적용여부';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_MOBILE_ICON_FILE_ID IS '모바일아이콘파일아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_LAYOUT_ID IS '레이아웃설정아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_ALLOW_URL_ID IS '허용URL아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_ALLOW_IP_ID IS '허용IP아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_ACCES_PROH_WORDS IS '접근금지문구';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_USER_JOIN_USE_FL IS '회원가입사용여부';

COMMENT ON COLUMN T_CORE_SETTING_BASIC.C_FOOTER_SCRIPT IS '하단스크립트';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_BASIC
	ON T_CORE_SETTING_BASIC (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_BASIC
	ADD
		CONSTRAINT PK_T_CORE_SETTING_BASIC
		PRIMARY KEY (
			C_ID
		);

/* TRIGGER_T_CORE_SETTING_BASIC */
/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
CREATE TABLE T_CORE_SETTING_BASIC_LOG
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE)                            NOT NULL,
  C_METHOD    VARCHAR2(4000 BYTE),
  C_STATE     VARCHAR2(4000 BYTE),
  C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_CORE_SETTING_BASIC_LOG IS '기본 트리 스키마 트리거 로그';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LOG.C_DATE IS '노드 변경 시'; 

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER TRIGGER_CORE_SETTING_BASIC
BEFORE DELETE OR INSERT OR UPDATE
ON T_CORE_SETTING_BASIC
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;
    IF UPDATING  THEN    
        insert into T_CORE_SETTING_BASIC_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);        
        insert into T_CORE_SETTING_BASIC_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);   
     END IF;
    IF DELETING THEN
        insert into T_CORE_SETTING_BASIC_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
    END IF;   
    IF INSERTING  THEN
        insert into T_CORE_SETTING_BASIC_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
    END IF;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END TRIGGER_CORE_SETTING_BASIC;

/* 일반설정_파일 */
CREATE TABLE T_CORE_SETTING_FILE (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_SAVED_NAME VARCHAR2(50), /* 저장파일이름 */
	C_EXTENSION NUMBER, /* 파일확장자 */
	C_ATTACHE_FILE NUMBER, /* 파일첨부유형 */
	C_CREATE_DT CHAR(14), /* 생성일시 */
	C_ORGINAL_NAME VARCHAR2(200) /* 원본파일이름 */
);

COMMENT ON TABLE T_CORE_SETTING_FILE IS '일반설정_파일';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_SAVED_NAME IS '저장파일이름';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_EXTENSION IS '파일확장자';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_ATTACHE_FILE IS '파일첨부유형';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_CREATE_DT IS '생성일시';

COMMENT ON COLUMN T_CORE_SETTING_FILE.C_ORGINAL_NAME IS '원본파일이름';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_FILE
	ON T_CORE_SETTING_FILE (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_FILE
	ADD
		CONSTRAINT PK_T_CORE_SETTING_FILE
		PRIMARY KEY (
			C_ID
		);

/* 일반설정_허용_URL */
CREATE TABLE T_CORE_SETTING_ALLOW_URL (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ALLOW_URL IS '일반설정_허용_URL';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_ALLOW_URL
	ON T_CORE_SETTING_ALLOW_URL (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ALLOW_URL
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ALLOW_URL
		PRIMARY KEY (
			C_ID
		);

/* 트리거 일반설정_허용_URL */
/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
CREATE TABLE T_CORE_SETTING_ALLOW_URL_LOG
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE)                            NOT NULL,
  C_METHOD    VARCHAR2(4000 BYTE),
  C_STATE     VARCHAR2(4000 BYTE),
  C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_CORE_SETTING_ALLOW_URL_LOG IS '기본 트리 스키마 트리거 로그';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_URL_LOG.C_DATE IS '노드 변경 시'; 

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER TRIGGER_CORE_SETTING_ALLOW_URL
BEFORE DELETE OR INSERT OR UPDATE
ON T_CORE_SETTING_ALLOW_URL
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;
    IF UPDATING  THEN    
        insert into T_CORE_SETTING_ALLOW_URL_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);        
        insert into T_CORE_SETTING_ALLOW_URL_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);   
     END IF;
    IF DELETING THEN
        insert into T_CORE_SETTING_ALLOW_URL_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
    END IF;   
    IF INSERTING  THEN
        insert into T_CORE_SETTING_ALLOW_URL_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
    END IF;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END TRIGGER_CORE_SETTING_ALLOW_URL;

/* 코어_설정_메일 */
CREATE TABLE T_CORE_SETTING_MAIL (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_EMAIL_CN VARCHAR2(4000), /* 메일내용 */
	C_MANAGER_NM VARCHAR2(200), /* 관리자명 */
	C_MANAGER_EMAIL_ID VARCHAR2(200), /* 관리자이메일아이디 */
	C_MANAGER_EMAIL_URL VARCHAR2(320), /* 관리자이메일URL */
	C_AUTO_SEND_FL CHAR(1) DEFAULT 0, /* 자동발송여부 */
	C_EMAIL_SEND_TARGET_ID NUMBER /* 메일발송대상아이디 */
);

COMMENT ON TABLE T_CORE_SETTING_MAIL IS '코어_설정_메일';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_EMAIL_CN IS '메일내용';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_MANAGER_NM IS '관리자명';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_MANAGER_EMAIL_ID IS '관리자이메일아이디';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_MANAGER_EMAIL_URL IS '관리자이메일URL';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_AUTO_SEND_FL IS '자동발송여부';

COMMENT ON COLUMN T_CORE_SETTING_MAIL.C_EMAIL_SEND_TARGET_ID IS '메일발송대상아이디';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_MAIL
	ON T_CORE_SETTING_MAIL (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_MAIL
	ADD
		CONSTRAINT PK_T_CORE_SETTING_MAIL
		PRIMARY KEY (
			C_ID
		);

/* 일반설정_기본_언어 */
CREATE TABLE T_CORE_SETTING_BASIC_LANGUAGE (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_BASIC_LANGUAGE IS '일반설정_기본_언어';

COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_BASIC_LANGUAGE
	ON T_CORE_SETTING_BASIC_LANGUAGE (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_BASIC_LANGUAGE
	ADD
		CONSTRAINT PK_T_CORE_SETTING_BASIC_LANGUAGE
		PRIMARY KEY (
			C_ID
		);

/* 트리거 일반설정_기본언어 */
/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
CREATE TABLE T_CORE_SETTING_BASIC_LANGUAGE_LOG
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE)                            NOT NULL,
  C_METHOD    VARCHAR2(4000 BYTE),
  C_STATE     VARCHAR2(4000 BYTE),
  C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_CORE_SETTING_BASIC_LANGUAGE_LOG IS '기본 트리 스키마 트리거 로그';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_CORE_SETTING_BASIC_LANGUAGE_LOG.C_DATE IS '노드 변경 시'; 

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER TRIGGER_CORE_SETTING_BASIC_LANGUAGE
BEFORE DELETE OR INSERT OR UPDATE
ON T_CORE_SETTING_BASIC_LANGUAGE
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;
    IF UPDATING  THEN    
        insert into T_CORE_SETTING_BASIC_LANGUAGE_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);        
        insert into T_CORE_SETTING_BASIC_LANGUAGE_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);   
     END IF;
    IF DELETING THEN
        insert into T_CORE_SETTING_BASIC_LANGUAGE_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
    END IF;   
    IF INSERTING  THEN
        insert into T_CORE_SETTING_BASIC_LANGUAGE_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
    END IF;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END TRIGGER_CORE_SETTING_BASIC_LANGUAGE;

/* 코어_설정_문자 */
CREATE TABLE T_CORE_SETTING_SMS (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	SMS_USE_FL CHAR(1) DEFAULT 0, /* 문자메시지사용여부 */
	SMS_ID VARCHAR2(200), /* 문자메시지아이디 */
	SMS_PASSWORD VARCHAR2(512), /* 문자메시지비밀번호 */
	SMS_SEND_TARGET_ID NUMBER, /* 문자메시지전송대상아이디 */
	SMS_SUBJECT VARCHAR2(200), /* 문자메시지제목 */
	SMS_CONTENT VARCHAR2(4000) /* 문자메시지내용 */
);

COMMENT ON TABLE T_CORE_SETTING_SMS IS '코어_설정_문자';

COMMENT ON COLUMN T_CORE_SETTING_SMS.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_SMS.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_SMS.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_SMS.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_SMS.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_SMS.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_SMS.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_SMS.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_SMS.SMS_USE_FL IS '문자메시지사용여부';

COMMENT ON COLUMN T_CORE_SETTING_SMS.SMS_ID IS '문자메시지아이디';

COMMENT ON COLUMN T_CORE_SETTING_SMS.SMS_PASSWORD IS '문자메시지비밀번호';

COMMENT ON COLUMN T_CORE_SETTING_SMS.SMS_SEND_TARGET_ID IS '문자메시지전송대상아이디';

COMMENT ON COLUMN T_CORE_SETTING_SMS.SMS_SUBJECT IS '문자메시지제목';

COMMENT ON COLUMN T_CORE_SETTING_SMS.SMS_CONTENT IS '문자메시지내용';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_SMS
	ON T_CORE_SETTING_SMS (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_SMS
	ADD
		CONSTRAINT PK_T_CORE_SETTING_SMS
		PRIMARY KEY (
			C_ID
		);

/* 일반설정_허용_IP */
CREATE TABLE T_CORE_SETTING_ALLOW_IP (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_CORE_SETTING_ALLOW_IP IS '일반설정_허용_IP';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP.C_TITLE IS '노드명';

COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP.C_TYPE IS '노드타입';

CREATE UNIQUE INDEX PK_T_CORE_SETTING_ALLOW_IP
	ON T_CORE_SETTING_ALLOW_IP (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ALLOW_IP
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ALLOW_IP
		PRIMARY KEY (
			C_ID
		);

/* 트리거 일반설정_허용_IP */
/*
 * JsTree 추적 로그 테이블
 * 트리거 Log를 저장합니다.
 */
CREATE TABLE T_CORE_SETTING_ALLOW_IP_LOG
(
  C_ID        NUMBER                            NOT NULL,
  C_PARENTID  NUMBER                            NOT NULL,
  C_POSITION  NUMBER                            NOT NULL,
  C_LEFT      NUMBER                            NOT NULL,
  C_RIGHT     NUMBER                            NOT NULL,
  C_LEVEL     NUMBER                            NOT NULL,
  C_TITLE     VARCHAR2(4000 BYTE),
  C_TYPE      VARCHAR2(4000 BYTE)                            NOT NULL,
  C_METHOD    VARCHAR2(4000 BYTE),
  C_STATE     VARCHAR2(4000 BYTE),
  C_DATE      DATE                              NOT NULL
);

COMMENT ON TABLE T_CORE_SETTING_ALLOW_IP_LOG IS '기본 트리 스키마 트리거 로그';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_ID IS '노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_PARENTID IS '부모 노드 아이디';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_POSITION IS '노드 포지션';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_LEFT IS '노드 좌측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_RIGHT IS '노드 우측 끝 포인트';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_LEVEL IS '노드 DEPTH ';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_TITLE IS '노드 명';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_TYPE IS '노드 타입';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_METHOD IS '노드 변경 행위';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_STATE IS '노드 상태값 ( 이전인지. 이후인지)';
COMMENT ON COLUMN T_CORE_SETTING_ALLOW_IP_LOG.C_DATE IS '노드 변경 시'; 

/*
 * JsTree 트리거
 */
CREATE OR REPLACE TRIGGER TRIGGER_CORE_SETTING_ALLOW_IP
BEFORE DELETE OR INSERT OR UPDATE
ON T_CORE_SETTING_ALLOW_IP
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;
    IF UPDATING  THEN    
        insert into T_CORE_SETTING_ALLOW_IP_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'update','변경이전데이터',sysdate);        
        insert into T_CORE_SETTING_ALLOW_IP_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'update','변경이후데이터',sysdate);   
     END IF;
    IF DELETING THEN
        insert into T_CORE_SETTING_ALLOW_IP_LOG 
        values (:old.C_ID,:old.C_PARENTID,:old.C_POSITION,:old.C_LEFT,:old.C_RIGHT,:old.C_LEVEL,:old.C_TITLE,:old.C_TYPE,'delete','삭제된데이터',sysdate);
    END IF;   
    IF INSERTING  THEN
        insert into T_CORE_SETTING_ALLOW_IP_LOG 
        values (:new.C_ID,:new.C_PARENTID,:new.C_POSITION,:new.C_LEFT,:new.C_RIGHT,:new.C_LEVEL,:new.C_TITLE,:new.C_TYPE,'insert','삽입된데이터',sysdate);
    END IF;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END TRIGGER_CORE_SETTING_ALLOW_IP;

/* 고급설정_설치프로그램_위젯_피드 */
CREATE TABLE T_CORE_SETTING_ADDON_WIDGET_FEED (
	C_ID NUMBER NOT NULL, /* 노드아이디 */
	C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
	C_POSITION NUMBER NOT NULL, /* 노드포지션 */
	C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
	C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
	C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
	C_TITLE VARCHAR2(4000), /* 노드명 */
	C_TYPE VARCHAR2(100), /* 노드타입 */
	C_URL VARCHAR2(255), /* URL */
	C_WIDGET_ID NUMBER /* 위젯매핑아이디 */
);

COMMENT ON TABLE T_CORE_SETTING_ADDON_WIDGET_FEED IS '고급설정_설치프로그램_후보군_타입 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_FEED.C_ID IS '노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_FEED.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_FEED.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_FEED.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_FEED.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_FEED.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_FEED.C_TITLE IS '노드명 - 컴포넌트, 위젯, 레이아웃';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_FEED.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_FEED.C_URL IS 'URL';

COMMENT ON COLUMN T_CORE_SETTING_ADDON_WIDGET_FEED.C_WIDGET_ID IS '위젯매핑아이디';

CREATE UNIQUE INDEX PK_T_CR_STNG_ADN_WDGT_FEED
	ON T_CORE_SETTING_ADDON_WIDGET_FEED (
		C_ID ASC
	);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET_FEED
	ADD
		CONSTRAINT PK_T_CORE_SETTING_ADDON_WIDGET_FEED
		PRIMARY KEY (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_LAYOUT_FILE
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_LAYOUT_TO_T_CORE_SETTING_LAYOUT_FILE
		FOREIGN KEY (
			C_LAYOUT_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_LAYOUT (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_WIDGET_SKIN_TO_T_CORE_SETTING_ADDON_WIDGET
		FOREIGN KEY (
			C_WIDGET_SKIN_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_WIDGET_SKIN (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TO_T_CORE_SETTING_ADDON_WIDGET
		FOREIGN KEY (
			C_WIDGET_CONTENTS_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_WIDGET_CONTENTS (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE_TO_T_CORE_SETTING_ADDON_WIDGET
		FOREIGN KEY (
			C_WIDGET_CONTENTS_TYPE_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_WIDGET_CONTENTS_TYPE (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE_TO_T_CORE_SETTING_ADDON_WIDGET
		FOREIGN KEY (
			C_WIDGET_HTML_TYPE
		)
		REFERENCES T_CORE_SETTING_ADDON_WIDGET_HTML_TYPE (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE_TO_T_CORE_SETTING_ADDON_WIDGET
		FOREIGN KEY (
			C_WIDGET_LINK_TYPE_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_WIDGET_LINK_TYPE (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_WIDGET_SORT_TO_T_CORE_SETTING_ADDON_WIDGET
		FOREIGN KEY (
			C_WIDGET_SORT_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_WIDGET_SORT (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD_TO_T_CORE_SETTING_ADDON_WIDGET
		FOREIGN KEY (
			C_WIDGET_SORT_METHOD_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_WIDGET_SORT_METHOD (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_WIDGET_THUM_TO_T_CORE_SETTING_ADDON_WIDGET
		FOREIGN KEY (
			C_WIDGET_THUM_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_WIDGET_THUM (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET
	ADD
		CONSTRAINT FK_T_CORE_MENU_TO_T_CORE_SETTING_ADDON_WIDGET
		FOREIGN KEY (
			C_MENU_ID
		)
		REFERENCES T_CORE_MENU (
			C_ID
		);

ALTER TABLE T_CORE_MENU
	ADD
		CONSTRAINT FK_T_CORE_PAGE_TO_T_CORE_MENU
		FOREIGN KEY (
			C_PAGE_MAPPING_ID
		)
		REFERENCES T_CORE_PAGE (
			C_ID
		);

ALTER TABLE T_CORE_MENU
	ADD
		CONSTRAINT FK_T_MENU_AUTH_TO_T_CORE_MENU
		FOREIGN KEY (
			C_AUTH_ID
		)
		REFERENCES T_MENU_AUTH (
			C_ID
		);

ALTER TABLE T_CORE_PAGE
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_WIDGET_TO_T_CORE_PAGE
		FOREIGN KEY (
			C_WIDGET_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_WIDGET (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_RESERVE
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_RESERVE_TYPE_TO_T_CORE_SETTING_ADDON_RESERVE
		FOREIGN KEY (
			C_RESERVE_TYPE_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_RESERVE_TYPE (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_BASIC
	ADD
		CONSTRAINT FK_T_CORE_SETTING_BASIC_LANGUAGE_TO_T_CORE_SETTING_BASIC
		FOREIGN KEY (
			C_BASIC_LANGUAGE_ID
		)
		REFERENCES T_CORE_SETTING_BASIC_LANGUAGE (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_BASIC
	ADD
		CONSTRAINT FK_T_CORE_SETTING_LAYOUT_TO_T_CORE_SETTING_BASIC
		FOREIGN KEY (
			C_LAYOUT_ID
		)
		REFERENCES T_CORE_SETTING_LAYOUT (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_BASIC
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ALLOW_URL_TO_T_CORE_SETTING_BASIC
		FOREIGN KEY (
			C_ALLOW_URL_ID
		)
		REFERENCES T_CORE_SETTING_ALLOW_URL (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_BASIC
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ALLOW_IP_TO_T_CORE_SETTING_BASIC
		FOREIGN KEY (
			C_ALLOW_IP_ID
		)
		REFERENCES T_CORE_SETTING_ALLOW_IP (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_BASIC
	ADD
		CONSTRAINT FK_T_CORE_SETTING_LOCAL_TIME_TO_T_CORE_SETTING_BASIC
		FOREIGN KEY (
			C_LOCAL_TIME_ID
		)
		REFERENCES T_CORE_SETTING_LOCAL_TIME (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_BASIC
	ADD
		CONSTRAINT FK_T_CORE_SETTING_TIME_FORMAT_TO_T_CORE_SETTING_BASIC
		FOREIGN KEY (
			C_TIME_FORMAT_ID
		)
		REFERENCES T_CORE_SETTING_TIME_FORMAT (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_BASIC
	ADD
		CONSTRAINT FK_T_CORE_SETTING_THUM_METHOD_TO_T_CORE_SETTING_BASIC
		FOREIGN KEY (
			C_THUM_CREAT_METHOD_ID
		)
		REFERENCES T_CORE_SETTING_THUM_METHOD (
			C_ID
		);

ALTER TABLE T_CORE_SETTING_ADDON_WIDGET_FEED
	ADD
		CONSTRAINT FK_T_CORE_SETTING_ADDON_WIDGET_TO_T_CORE_SETTING_ADDON_WIDGET_FEED
		FOREIGN KEY (
			C_WIDGET_ID
		)
		REFERENCES T_CORE_SETTING_ADDON_WIDGET (
			C_ID
		);