/* 회원_금지단어 */
DROP TABLE T_USER_PROH_WORD;

CREATE TABLE T_USER_PROH_WORD (
    C_ID NUMBER NOT NULL, /* 노드아이디 */
    C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
    C_POSITION NUMBER NOT NULL, /* 노드포지션 */
    C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
    C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
    C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
    C_TITLE VARCHAR2(4000), /* 노드명 */
    C_TYPE VARCHAR2(100), /* 노드타입 */
    C_TYPE_CD CHAR(1) NOT NULL /* 유형코드 */
);

COMMENT ON TABLE T_USER_PROH_WORD IS '회원_금지단어';

COMMENT ON COLUMN T_USER_PROH_WORD.C_ID IS '노드아이디';

COMMENT ON COLUMN T_USER_PROH_WORD.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_USER_PROH_WORD.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_USER_PROH_WORD.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_USER_PROH_WORD.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_USER_PROH_WORD.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_USER_PROH_WORD.C_TITLE IS '노드명';

COMMENT ON COLUMN T_USER_PROH_WORD.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_USER_PROH_WORD.C_TYPE_CD IS '유형코드';

--CREATE UNIQUE INDEX PK_T_USER_PROH_WORD
--  ON T_USER_PROH_WORD (
--      C_ID ASC
--  );

ALTER TABLE T_USER_PROH_WORD
    ADD
        CONSTRAINT PK_T_USER_PROH_WORD
        PRIMARY KEY (
            C_ID
        );
        
DROP SEQUENCE S_USER_PROH_WORD;

CREATE SEQUENCE S_USER_PROH_WORD
  START WITH 7313
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;
  
/* 회원_이용약관 */
DROP TABLE T_USER_TERMS_OF_USE;
  
CREATE TABLE T_USER_TERMS_OF_USE (
    C_ID NUMBER NOT NULL, /* 노드아이디 */
    C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
    C_POSITION NUMBER NOT NULL, /* 노드포지션 */
    C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
    C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
    C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
    C_TITLE VARCHAR2(4000), /* 노드명 */
    C_TYPE VARCHAR2(100), /* 노드타입 */
    C_TYPE_CD CHAR(1) NOT NULL, /* 유형코드 */
    C_COMPANY_INTR VARCHAR2(4000) NOT NULL, /* 회사소개 */
    C_TERMS_OF_USE VARCHAR2(4000) NOT NULL, /* 이용약관 */
    C_PRIVACY_POLICY VARCHAR2(4000) NOT NULL /* 개인정보취급방침 */
);

COMMENT ON TABLE T_USER_TERMS_OF_USE IS '회원_이용약관';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_ID IS '노드아이디';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_TITLE IS '노드명';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_TYPE_CD IS '유형코드';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_COMPANY_INTR IS '회사소개';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_TERMS_OF_USE IS '이용약관';

COMMENT ON COLUMN T_USER_TERMS_OF_USE.C_PRIVACY_POLICY IS '개인정보취급방침';

--CREATE UNIQUE INDEX PK_T_USER_TERMS_OF_USE
--  ON T_USER_TERMS_OF_USE (
--      C_ID ASC
--  );

ALTER TABLE T_USER_TERMS_OF_USE
    ADD
        CONSTRAINT PK_T_USER_TERMS_OF_USE
        PRIMARY KEY (
            C_ID
        );

DROP SEQUENCE S_USER_TERMS_OF_USE;

CREATE SEQUENCE S_USER_TERMS_OF_USE
  START WITH 7313
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;
  
/* 회원_가입필드컴포넌트 */
DROP TABLE T_USER_JOIN_FIELD_COMP;
  
CREATE TABLE T_USER_JOIN_FIELD_COMP (
    C_ID NUMBER NOT NULL, /* 노드아이디 */
    C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
    C_POSITION NUMBER NOT NULL, /* 노드포지션 */
    C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
    C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
    C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
    C_TITLE VARCHAR2(4000), /* 노드명 */
    C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_USER_JOIN_FIELD_COMP IS '회원_가입필드컴포넌트';

COMMENT ON COLUMN T_USER_JOIN_FIELD_COMP.C_ID IS '노드아이디';

COMMENT ON COLUMN T_USER_JOIN_FIELD_COMP.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_USER_JOIN_FIELD_COMP.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_USER_JOIN_FIELD_COMP.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_USER_JOIN_FIELD_COMP.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_USER_JOIN_FIELD_COMP.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_USER_JOIN_FIELD_COMP.C_TITLE IS '노드명';

COMMENT ON COLUMN T_USER_JOIN_FIELD_COMP.C_TYPE IS '노드타입';

--CREATE UNIQUE INDEX PK_T_USER_JOIN_FIELD_COMP
--  ON T_USER_JOIN_FIELD_COMP (
--      C_ID ASC
--  );

ALTER TABLE T_USER_JOIN_FIELD_COMP
    ADD
        CONSTRAINT PK_T_USER_JOIN_FIELD_COMP
        PRIMARY KEY (
            C_ID
        );

DROP SEQUENCE S_USER_JOIN_FIELD_COMP;

CREATE SEQUENCE S_USER_JOIN_FIELD_COMP
  START WITH 7313
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;
  
/* 회원_가입필드 */
DROP TABLE T_USER_JOIN_FIELD;
  
CREATE TABLE T_USER_JOIN_FIELD (
    C_ID NUMBER NOT NULL, /* 노드아이디 */
    C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
    C_POSITION NUMBER NOT NULL, /* 노드포지션 */
    C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
    C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
    C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
    C_TITLE VARCHAR2(4000), /* 노드명 */
    C_TYPE VARCHAR2(100), /* 노드타입 */
    C_COMP_KIND_CD NUMBER NOT NULL, /* 컴포넌트종류코드 */
    C_USE_FL CHAR(1) DEFAULT 0 NOT NULL, /* 사용여부 */
    C_INFO_OPEN_FL CHAR(1) DEFAULT 0 NOT NULL, /* 정보공개여부 */
    C_ESSE_INPUT_FL CHAR(1) DEFAULT 0 NOT NULL /* 필수입력여부 */
);

COMMENT ON TABLE T_USER_JOIN_FIELD IS '회원_가입필드';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_ID IS '노드아이디';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_TITLE IS '노드명';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_COMP_KIND_CD IS '컴포넌트종류코드';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_USE_FL IS '사용여부';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_INFO_OPEN_FL IS '정보공개여부';

COMMENT ON COLUMN T_USER_JOIN_FIELD.C_ESSE_INPUT_FL IS '필수입력여부';

--CREATE UNIQUE INDEX PK_T_USER_JOIN_FIELD
--  ON T_USER_JOIN_FIELD (
--      C_ID ASC
--  );

ALTER TABLE T_USER_JOIN_FIELD
    ADD
        CONSTRAINT PK_T_USER_JOIN_FIELD
        PRIMARY KEY (
            C_ID
        );

ALTER TABLE T_USER_JOIN_FIELD
    ADD
        CONSTRAINT FK_T_USER_JOIN_FIELD_COMP
        FOREIGN KEY (
            C_COMP_KIND_CD
        )
        REFERENCES T_USER_JOIN_FIELD_COMP (
            C_ID
        );

DROP SEQUENCE S_USER_JOIN_FIELD;

CREATE SEQUENCE S_USER_JOIN_FIELD
  START WITH 7313
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;

/* 회원_비밀번호보안수준 */
DROP TABLE T_USER_PASSWORD_SECURITY_LEVEL;

CREATE TABLE T_USER_PASSWORD_SECURITY_LEVEL (
    C_ID NUMBER NOT NULL, /* 노드 아이디 */
    C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
    C_POSITION NUMBER NOT NULL, /* 노드포지션 */
    C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
    C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
    C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
    C_TITLE VARCHAR2(4000), /* 노드명 */
    C_TYPE VARCHAR2(100) /* 노드타입 */
);

COMMENT ON TABLE T_USER_PASSWORD_SECURITY_LEVEL IS '회원_비밀번호보안수준';

COMMENT ON COLUMN T_USER_PASSWORD_SECURITY_LEVEL.C_ID IS '노드 아이디';

COMMENT ON COLUMN T_USER_PASSWORD_SECURITY_LEVEL.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_USER_PASSWORD_SECURITY_LEVEL.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_USER_PASSWORD_SECURITY_LEVEL.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_USER_PASSWORD_SECURITY_LEVEL.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_USER_PASSWORD_SECURITY_LEVEL.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_USER_PASSWORD_SECURITY_LEVEL.C_TITLE IS '노드명';

COMMENT ON COLUMN T_USER_PASSWORD_SECURITY_LEVEL.C_TYPE IS '노드타입';

--CREATE UNIQUE INDEX PK_T_USER_PWD_SECU_LEVEL
--  ON T_USER_PASSWORD_SECURITY_LEVEL (
--      C_ID ASC
--  );

ALTER TABLE T_USER_PASSWORD_SECURITY_LEVEL
    ADD
        CONSTRAINT PK_T_USER_PWD_SECU_LEVEL
        PRIMARY KEY (
            C_ID
        );

ALTER TABLE T_USER_BASIC_SETTING
    ADD
        CONSTRAINT FK_T_USER_PWD_SECU_LEVEL
        FOREIGN KEY (
            C_PASSWORD_SECURITY_LEVEL_CD
        )
        REFERENCES T_USER_PASSWORD_SECURITY_LEVEL (
            C_ID
        );
    
DROP SEQUENCE S_USER_PASSWORD_SECURITY_LEVEL;

CREATE SEQUENCE S_USER_PASSWORD_SECURITY_LEVEL
  START WITH 7313
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;
  
/* 회원_기본설정 */
DROP TABLE T_USER_BASIC_SETTING;
  
CREATE TABLE T_USER_BASIC_SETTING (
    C_ID NUMBER NOT NULL, /* 노드아이디 */
    C_PARENTID NUMBER NOT NULL, /* 부모노드아이디 */
    C_POSITION NUMBER NOT NULL, /* 노드포지션 */
    C_LEFT NUMBER NOT NULL, /* 노드좌측끝포인트 */
    C_RIGHT NUMBER NOT NULL, /* 노드우측끝포인트 */
    C_LEVEL NUMBER NOT NULL, /* 노드레벨 */
    C_TITLE VARCHAR2(4000), /* 노드명 */
    C_TYPE VARCHAR2(100), /* 노드타입 */
    C_WEB_MASTER_NM VARCHAR2(30) NOT NULL, /* 웹마스터이름 */
    C_WEB_MASTER_EMAIL VARCHAR2(320) NOT NULL, /* 웹마스터이메일 */
    C_JOIN_APPROVAL_FL CHAR(1) DEFAULT 0 NOT NULL, /* 가입승인여부 */
    C_EMAIL_AUTH_USE_FL CHAR(1) DEFAULT 0 NOT NULL, /* 이메일인증사용여부 */
    C_PASSWORD_SECURITY_LEVEL_CD NUMBER NOT NULL, /* 비밀번호보안수준코드 */
    C_PASSWORD_CHANGE_DCNT NUMBER(3) NOT NULL, /* 비밀번호변경일수 */
    C_LOGIN_LIMIT_DCNT NUMBER(2) NOT NULL, /* 로그인제한일수 */
    C_LOGIN_FAILURE_LIMIT_CNT NUMBER(1) NOT NULL /* 로그인실패제한횟수 */
);

COMMENT ON TABLE T_USER_BASIC_SETTING IS '회원_기본설정';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_ID IS '노드아이디';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_PARENTID IS '부모노드아이디';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_POSITION IS '노드포지션';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_LEFT IS '노드좌측끝포인트';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_RIGHT IS '노드우측끝포인트';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_LEVEL IS '노드레벨';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_TITLE IS '노드명';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_TYPE IS '노드타입';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_WEB_MASTER_NM IS '웹마스터이름';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_WEB_MASTER_EMAIL IS '웹마스터이메일';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_JOIN_APPROVAL_FL IS '가입승인여부';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_EMAIL_AUTH_USE_FL IS '이메일인증사용여부';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_PASSWORD_SECURITY_LEVEL_CD IS '비밀번호보안수준코드';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_PASSWORD_CHANGE_DCNT IS '비밀번호변경일수';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_LOGIN_LIMIT_DCNT IS '로그인제한일수';

COMMENT ON COLUMN T_USER_BASIC_SETTING.C_LOGIN_FAILURE_LIMIT_CNT IS '로그인실패제한횟수';

--CREATE UNIQUE INDEX PK_T_USER_BASIC_SETTING
--  ON T_USER_BASIC_SETTING (
--      C_ID ASC
--  );

ALTER TABLE T_USER_BASIC_SETTING
    ADD
        CONSTRAINT PK_T_USER_BASIC_SETTING
        PRIMARY KEY (
            C_ID
        );

DROP SEQUENCE S_USER_BASIC_SETTING;

CREATE SEQUENCE S_USER_BASIC_SETTING
  START WITH 7313
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;