CREATE TABLE T_SECURE_USER
(
  C_ID                 NUMBER                   NOT NULL,
  C_PARENTID           NUMBER                   NOT NULL,
  C_POSITION           NUMBER                   NOT NULL,
  C_LEFT               NUMBER                   NOT NULL,
  C_RIGHT              NUMBER                   NOT NULL,
  C_LEVEL              NUMBER                   NOT NULL,
  C_TITLE              VARCHAR2(4000 BYTE)      NOT NULL,
  C_TYPE               VARCHAR2(100 BYTE),
  C_PASSWORD           VARCHAR2(256 BYTE)       NOT NULL,
  C_EMAIL              VARCHAR2(320 BYTE)       NOT NULL,
  C_LOGIN_FAILURE_CNT  NUMBER(1)                DEFAULT 0                     NOT NULL,
  C_JOIN_DT            CHAR(14 BYTE)            NOT NULL,
  C_LAST_LOGIN_DT      CHAR(14 BYTE)
)

COMMENT ON TABLE T_SECURE_USER IS '회원_정보';
COMMENT ON COLUMN T_SECURE_USER.C_ID IS '노드아이디';
COMMENT ON COLUMN T_SECURE_USER.C_PARENTID IS '부모노드아이디';
COMMENT ON COLUMN T_SECURE_USER.C_POSITION IS '노드포지션';
COMMENT ON COLUMN T_SECURE_USER.C_LEFT IS '노드좌측끝포인트';
COMMENT ON COLUMN T_SECURE_USER.C_RIGHT IS '노드우측끝포인트';
COMMENT ON COLUMN T_SECURE_USER.C_LEVEL IS '노드레벨';
COMMENT ON COLUMN T_SECURE_USER.C_TITLE IS '닉네임';
COMMENT ON COLUMN T_SECURE_USER.C_TYPE IS '노드타입';
COMMENT ON COLUMN T_SECURE_USER.C_PASSWORD IS '비밀번호';
COMMENT ON COLUMN T_SECURE_USER.C_EMAIL IS '이메일';
COMMENT ON COLUMN T_SECURE_USER.C_LOGIN_FAILURE_CNT IS '로그인실패횟수';
COMMENT ON COLUMN T_SECURE_USER.C_JOIN_DT IS '가입일시';
COMMENT ON COLUMN T_SECURE_USER.C_LAST_LOGIN_DT IS '마지막로그인일시';

DROP SEQUENCE S_SECURE_USER;

CREATE SEQUENCE S_SECURE_USER
  START WITH 10
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;
