/* T_PRIMARY_COMPREHENSIVETREE */

/* Insert Root Node */
INSERT INTO T_PRIMARY_COMPREHENSIVETREE(C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE, F_C_ID)
VALUES (1, 0, 0, 1, 6, 0, 'Root Node', NULL, 1);

/* Insert 1st Child Node */
INSERT INTO T_PRIMARY_COMPREHENSIVETREE(C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE, F_C_ID)
VALUES (2, 1, 0, 2, 5, 0, 'Account', 'drive', 1);

/* Insert 2nd Child Node */
INSERT INTO T_PRIMARY_COMPREHENSIVETREE(C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE, F_C_ID)
VALUES (3, 2, 0, 3, 4, 1, 'Name', 'folder', 1);

COMMIT;

/* T_FOREIGN_COMPREHENSIVETREE */

/* Insert Root Node */
INSERT INTO T_FOREIGN_COMPREHENSIVETREE(C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE)
VALUES (1, 0, 0, 1, 6, 0, 'Root Node', NULL);

/* Insert 1st Child Node */
INSERT INTO T_FOREIGN_COMPREHENSIVETREE(C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE)
VALUES (2, 1, 0, 2, 5, 0, 'Authority', 'drive');

/* Insert 2nd Child Node */
INSERT INTO T_FOREIGN_COMPREHENSIVETREE(C_ID, C_PARENTID, C_POSITION, C_LEFT, C_RIGHT, C_LEVEL, C_TITLE, C_TYPE)
VALUES (3, 2, 0, 3, 4, 1, 'Level', 'folder');

COMMIT;